String.toLocaleString({
    "en": {
        "%welcomeback": "Welcome Back!",
        "%loginwithyouremailtext": "Log in with your email to access Neeter.",
        "%login-button": "Login",
        "%sign-up-instead": "Sign up instead",
        "%forgot-password": "Forgot Your password?",
        "%hellothere": "Hello There!",
        "%welcometoneeter": "Welcome to Neeter! Please enter your details to create an account.",
        "%register-button": "Register",
        "%login-instead": "Login instead",
        "%login-email-input": "Email",
        "%login-password-input": "Password",
        "%reg-email-input": "Email",
        "%reg-password-input": "Password",
        "%reg-username-input": "Username"
    },
    "es": {
        "%welcomeback": "¡Bienvenido de nuevo!",
        "%loginwithyouremailtext": "Inicia sesión con tu correo electrónico para acceder a Neeter.",
        "%login-button": "Iniciar sesión",
        "%sign-up-instead": "Regístrate en su lugar",
        "%forgot-password": "¿Olvidaste tu contraseña?",
        "%hellothere": "¡Hola!",
        "%welcometoneeter": "¡Bienvenido a Neeter! Por favor, introduce tus datos para crear una cuenta.",
        "%register-button": "Registrarse",
        "%login-instead": "Iniciar sesión en su lugar",
        "%login-email-input": "Correo electrónico",
        "%login-password-input": "Contraseña",
        "%reg-email-input": "Correo electrónico",
        "%reg-password-input": "Contraseña",
        "%reg-username-input": "Nombre de usuario"
    },
    "ca": {
        "%welcomeback": "Benvingut de nou!",
        "%loginwithyouremailtext": "Inicieu la sessió amb el vostre correu electrònic per accedir a Neeter.",
        "%login-button": "Iniciar sessió",
        "%sign-up-instead": "Registreu-vos",
        "%forgot-password": "Heu oblidat la vostra contrasenya?",
        "%hellothere": "Hola!",
        "%welcometoneeter": "Benvingut a Neeter! Si us plau, introdueixi les seves dades per crear un compte.",
        "%register-button": "Registrar-se",
        "%login-instead": "Iniciar sessió",
        "%login-email-input": "Correu electrònic",
        "%login-password-input": "Contrasenya",
        "%reg-email-input": "Correu electrònic",
        "%reg-password-input": "Contrasenya",
        "%reg-username-input": "Nom d'usuari"
    },
    "fr": {
        "%welcomeback": "Bienvenue de retour!",
        "%loginwithyouremailtext": "Connectez-vous avec votre e-mail pour accéder à Neeter.",
        "%login-button": "S'identifier",
        "%sign-up-instead": "S'inscrire",
        "%forgot-password": "Mot de passe oublié?",
        "%hellothere": "Bonjour!",
        "%welcometoneeter": "Bienvenue sur Neeter! Veuillez saisir vos coordonnées pour créer un compte.",
        "%register-button": "S'inscrire",
        "%login-instead": "S'identifier",
        "%login-email-input": "Email",
        "%login-password-input": "Mot de passe",
        "%reg-email-input": "Email",
        "%reg-password-input": "Mot de passe",
        "%reg-username-input": "Nom d'utilisateur"
    },
    "hi": {
        "%welcomeback": "वापसी पर स्वागत है!",
        "%loginwithyouremailtext": "नीटर तक पहुंच के लिए अपने ईमेल से लॉगिन करें।",
        "%login-button": "लॉग इन करें",
        "%sign-up-instead": "इसके बजाय साइन अप करें",
        "%forgot-password": "क्या आपने अपना पासवर्ड भूल गए?",
        "%hellothere": "नमस्ते!",
        "%welcometoneeter": "नीटर में आपका स्वागत है! कृपया अपना विवरण दर्ज करें और खाता बनाएं।",
        "%register-button": "रजिस्टर",
        "%login-instead": "इसके बजाय लॉगिन करें",
        "%login-email-input": "ईमेल",
        "%login-password-input": "पारण शब्द",
        "%reg-email-input": "ईमेल",
        "%reg-password-input": "पारण शब्द",
        "%reg-username-input": "उपयोगकर्ता नाम"
    },
    "te": {
        "%welcomeback": "తిరిగి స్వాగతం!",
        "%loginwithyouremailtext": "నీటర్‌కు ప్రవేశించడానికి మీ ఇమెయిల్‌తో లాగిన్ చేయండి.",
        "%login-button": "లాగిన్",
        "%sign-up-instead": "సైన్ అప్ చేయండి",
        "%forgot-password": "మీ పాస్‌వర్డ్‌ను మర్చిపోయారా?",
        "%hellothere": "హలో!",
        "%welcometoneeter": "నీటర్‌కు స్వాగతం! దయచేసి మీ వివరాలను నమోదు చేయండి మరియు ఖాతాను సృష్టించండి.",
        "%register-button": "నమోదు",
        "%login-instead": "సైన్ ఇన్ చేయండి",
        "%login-email-input": "ఇమెయిల్",
        "%login-password-input": "పాస్‌వర్డ్",
        "%reg-email-input": "ఇమెయిల్",
        "%reg-password-input": "పాస్‌వర్డ్",
        "%reg-username-input": "వాడుకరి పేరు"
    }
});