String.toLocaleString({
	"en": {
		"%logoutbutton": "Logout",
		"%circlesettings": "Circle Settings",
		"%replyingtext": "Replying",
		"%editingmsg": "Editing a message ",
		"%cancelreplyoredit": "Cancel",
		"%typeamessage": "Type a message...",
		"%ratelimit": "Whoa! You're going too fast! Slow down a bit and try again.",
		"%closecirclesettings": "Close Settings",
		"%circlesettingstitle": "Circle Settings",
		"%circlename": "Circle Name",
		"%circledescription": "Circle Description",
		"%circleicon": "Circle Icon (Emoji)",
		"%savecirclesettings": "Save",
		"%leavingmodal": "You are about to leave Neeter and go to an external website. Are you sure you want to continue?",
		"%confirmLeaveNeeterButton": "Confirm",
		"%closeLeaveNeeterModal": "Cancel"
	},
	"es": {
		"%logoutbutton": "Cerrar sesión",
		"%circlesettings": "Preferencias del círculo",
		"%replyingtext": "Respondiendo",
		"%editingmsg": "Editando un mensaje ",
		"%cancelreplyoredit": "Cancelar",
		"%typeamessage": "Escribe un mensaje...",
		"%ratelimit": "¡Espera! ¡Vas demasiado rápido! Baja un poco la velocidad e inténtalo de nuevo.",
		"%closecirclesettings": "Cerrar ajustes",
		"%circlesettingstitle": "Ajustes del círculo",
		"%circlename": "Nombre del círculo",
		"%circledescription": "Descripción del círculo",
		"%circleicon": "Icono del círculo (Emoji)",
		"%savecirclesettings": "Guardar",
		"%leavingmodal": "Estás a punto de salir de Neeter y visitar una página web externa. ¿Estás seguro de que quieres continuar?",
		"%confirmLeaveNeeterButton": "Confirmar",
		"%closeLeaveNeeterModal": "Cancelar"
	},
	"ca": {
		"%logoutbutton": "Tancar sessió",
		"%circlesettings": "Preferències del cercle",
		"%replyingtext": "Respondre",
		"%editingmsg": "Editant un missatge ",
		"%cancelreplyoredit": "Cancel·lar",
		"%typeamessage": "Escriu un missatge...",
		"%ratelimit": "Espera! Vas massa ràpid! Baixa una mica la velocitat i torna-ho a provar.",
		"%closecirclesettings": "Tancar ajustos",
		"%circlesettingstitle": "Ajustos del cercle",
		"%circlename": "Nom del cercle",
		"%circledescription": "Descripció del cercle",
		"%circleicon": "Icona del cercle (Emoji)",
		"%savecirclesettings": "Guardar",
		"%leavingmodal": "Estàs a punt de sortir de Neeter i visitar una pàgina web externa. Estàs segur que vols continuar?",
		"%confirmLeaveNeeterButton": "Confirmar",
		"%closeLeaveNeeterModal": "Cancel·lar"
	},
	"fr": {
		"%logoutbutton": "Déconnexion",
		"%circlesettings": "Paramètres du cercle",
		"%replyingtext": "Répondre",
		"%editingmsg": "Modifier un message ",
		"%cancelreplyoredit": "Annuler",
		"%typeamessage": "Écrire un message...",
		"%ratelimit": "Hé ! Tu vas trop vite ! Ralentis un peu et réessaie.",
		"%closecirclesettings": "Fermer les paramètres",
		"%circlesettingstitle": "Paramètres du cercle",
		"%circlename": "Nom du cercle",
		"%circledescription": "Description du cercle",
		"%circleicon": "Icône du cercle (Emoji)",
		"%savecirclesettings": "Enregistrer",
		"%leavingmodal": "Vous êtes sur le point de quitter Neeter et d'accéder à un site externe. Êtes-vous sûr de vouloir continuer ?",
		"%confirmLeaveNeeterButton": "Confirmer",
		"%closeLeaveNeeterModal": "Annuler"
	},
	"hi": {
		"%logoutbutton": "लॉग आउट",
		"%circlesettings": "सर्कल सेटिंग्स",
		"%replyingtext": "जवाब दे रहा है",
		"%editingmsg": "संदेश संपादित कर रहा है ",
		"%cancelreplyoredit": "रद्द करना",
		"%typeamessage": "एक संदेश लिखें...",
		"%ratelimit": "वहा! आप बहुत तेजी से जा रहे हैं! थोड़ा धीमा चलो और फिर से कोशिश करो.",
		"%closecirclesettings": "सेटिंग्स बंद करें",
		"%circlesettingstitle": "सर्कल सेटिंग्स",
		"%circlename": "सर्कल का नाम",
		"%circledescription": "सर्कल विवरण",
		"%circleicon": "सर्कल आइकन (इमोजी)",
		"%savecirclesettings": "सहेजें",
		"%leavingmodal": "आप नीटर छोड़ने वाले हैं और एक बाहरी वेबसाइट पर जा रहे हैं। क्या आप जारी रखना चाहते हैं?",
		"%confirmLeaveNeeterButton": "पुष्टि करें",
		"%closeLeaveNeeterModal": "रद्द करना"
	}
});